#!/usr/bin/env ruby

require "letter_sequence"

def run(list, n, klass)

  start_time = Time.now
  results = klass.new(list).find_sequences
  end_time = Time.now

  File.write("questions#{n}.out", results[:questions].sort.join("\n"))
  File.write("answers#{n}.out",   results[:answers].sort.join("\n"))

  puts "\nSEQUENCER RUN #{n}"
  puts "\nCompleted #{list.length} words in #{"%0.6f" % (end_time - start_time).to_f} seconds"
  puts "Number of questions: #{results[:questions].length}"
  puts "Number of answers: #{results[:answers].length}"

end

word_file = ARGV.shift

unless word_file
  warn "\nNo word file given"
  warn "\nUsage: #{$0} WORDFILE\n"
  exit -1
end

word_list = File.readlines(word_file).map{|w| w.chomp}

run(word_list, 1, LetterSequence::Sequencer)
